#!/bin/sh

export LANG=C.UTF-8
export LC_ALL=C.UTF-8

if [ -z "$HOME" ] || [ ! -d "$HOME" ]; then
    [ -e debian/tests.home ] || mkdir debian/tests.home
    export HOME="$(pwd)/debian/tests.home"
    trap "rm -rf debian/tests.home" EXIT
fi
mkdir -p "$HOME"/.config || true
mkdir -p "$HOME/runtime" || true
chmod 700 "$HOME/runtime"
export XDG_RUNTIME_DIR="$HOME/runtime"
xvfb-run -a --server-args="-screen 0 1024x768x24+32" \
    dh_auto_test --no-parallel
